/**
 * Journey data for Johnson's Journey.
 * Add new places here — map and filters update automatically.
 * status: "visited" or "to-visit"
 */
window.JOURNEYS = [
  // ——— Visited ———
  {
    id: 1,
    location: "Beijing, China",
    country: "China Mainland",
    year: 2019,
    date: "October 5, 2019",
    status: "visited",
    latitude: 39.9042,
    longitude: 116.4074,
    image: "images/journeys/beijing.svg",
    story: "Climbed the Great Wall at Mutianyu and wandered the hutongs afterward — one day felt like two different centuries."
  },
  {
    id: 2,
    location: "Hong Kong",
    country: "Hong Kong, China",
    year: 2018,
    date: "March 15, 2018",
    status: "visited",
    latitude: 22.3193,
    longitude: 114.1694,
    image: "images/journeys/hongkong.svg",
    story: "Rode the tram up Victoria Peak at dusk and watched the skyline light up. Dim sum every morning, no regrets."
  },
  {
    id: 3,
    location: "Macau",
    country: "Macau, China",
    year: 2018,
    date: "March 18, 2018",
    status: "visited",
    latitude: 22.1987,
    longitude: 113.5439,
    image: "images/journeys/macau.svg",
    story: "Portuguese egg tarts by the Ruins of St. Paul's — a quick hop from Hong Kong that felt like a different world."
  },
  {
    id: 4,
    location: "New York City, USA",
    country: "USA",
    year: 2022,
    date: "June 8, 2022",
    status: "visited",
    latitude: 40.7128,
    longitude: -74.006,
    image: "images/journeys/newyork.svg",
    story: "Walked the Brooklyn Bridge at sunrise, pizza by the slice, and a show that ran late — the city really doesn't sleep."
  },
  {
    id: 5,
    location: "Banff, Canada",
    country: "Canada",
    year: 2026,
    date: "July 18, 2026",
    status: "visited",
    latitude: 51.1784,
    longitude: -115.5708,
    image: "images/journeys/banff.jpg",
    story: "A memorable family trip through the Canadian Rockies — crisp air, turquoise lakes, and long walks that made the mountains feel close."
  },
  {
    id: 13,
    location: "White Rock, Canada",
    country: "Canada",
    year: 2025,
    date: "August 2, 2025",
    status: "visited",
    latitude: 49.0253,
    longitude: -122.8029,
    image: "images/journeys/whiterock.svg",
    story: "A long walk on the pier, fish and chips by the beach, and the white rock itself glowing in the afternoon sun."
  },
  {
    id: 14,
    location: "Calgary, Canada",
    country: "Canada",
    year: 2026,
    date: "July 10, 2026",
    status: "visited",
    latitude: 51.0447,
    longitude: -114.0719,
    image: "images/journeys/calgary.svg",
    story: "Stampede week — pancake breakfasts, rodeo afternoons, and the whole city in cowboy hats."
  },
  {
    id: 15,
    location: "Drumheller, Canada",
    country: "Canada",
    year: 2026,
    date: "July 12, 2026",
    status: "visited",
    latitude: 51.4636,
    longitude: -112.7095,
    image: "images/journeys/drumheller.svg",
    story: "Badlands, hoodoos, and a day among dinosaurs at the Royal Tyrrell Museum — like walking on another planet."
  },
  {
    id: 16,
    location: "Boundary Bay, Canada",
    country: "Canada",
    year: 2025,
    date: "May 24, 2025",
    status: "visited",
    latitude: 49.0728,
    longitude: -123.0338,
    image: "images/journeys/boundarybay.svg",
    story: "Low tide stretched the beach out forever — herons, sandpipers, and a picnic with the border mountains in view."
  },
  {
    id: 17,
    location: "Vancouver Chinatown, Canada",
    country: "Canada",
    year: 2024,
    date: "February 10, 2024",
    status: "visited",
    latitude: 49.2806,
    longitude: -123.1006,
    image: "images/journeys/vanchinatown.svg",
    story: "Lunar New Year in one of North America's oldest Chinatowns — lion dances, dim sum, and the Dr. Sun Yat-Sen garden."
  },
  {
    id: 18,
    location: "Calgary Chinatown, Canada",
    country: "Canada",
    year: 2026,
    date: "July 11, 2026",
    status: "visited",
    latitude: 51.0513,
    longitude: -114.0633,
    image: "images/journeys/calchinatown.svg",
    story: "Dumplings and bubble tea by the Bow River after a Stampede morning — the Chinese Cultural Centre's dome is a hidden gem."
  },
  {
    id: 19,
    location: "BC Parliament Buildings, Canada",
    country: "Canada",
    year: 2025,
    date: "September 6, 2025",
    status: "visited",
    latitude: 48.4198,
    longitude: -123.3706,
    image: "images/journeys/bcparliament.svg",
    story: "Took the ferry to Victoria and watched the Parliament Buildings light up over the Inner Harbour at dusk."
  },
  {
    id: 20,
    location: "Hope, Canada",
    country: "Canada",
    year: 2025,
    date: "August 3, 2025",
    status: "visited",
    latitude: 49.3858,
    longitude: -121.4419,
    image: "images/journeys/hope.svg",
    story: "A road-trip stop at the gateway to the canyon — chainsaw carvings in the park and mountains on every side."
  },
  {
    id: 21,
    location: "Yaletown, Canada",
    country: "Canada",
    year: 2024,
    date: "February 11, 2024",
    status: "visited",
    latitude: 49.2745,
    longitude: -123.1219,
    image: "images/journeys/yaletown.svg",
    story: "Brunch in a converted warehouse, then a slow loop of the seawall — Vancouver at its most relaxed."
  },
  {
    id: 22,
    location: "Lake Louise, Canada",
    country: "Canada",
    year: 2026,
    date: "July 19, 2026",
    status: "visited",
    latitude: 51.4254,
    longitude: -116.1773,
    image: "images/journeys/lakelouise.svg",
    story: "Canoes on impossibly turquoise water with Victoria Glacier behind — every photo looked fake and none of them were."
  },
  {
    id: 23,
    location: "Moraine Lake, Canada",
    country: "Canada",
    year: 2026,
    date: "July 19, 2026",
    status: "visited",
    latitude: 51.3217,
    longitude: -116.186,
    image: "images/journeys/morainelake.svg",
    story: "Sunrise at the Valley of the Ten Peaks — cold hands, hot coffee, and the bluest water of the whole trip."
  },
  {
    id: 24,
    location: "Bow Lake, Canada",
    country: "Canada",
    year: 2026,
    date: "July 20, 2026",
    status: "visited",
    latitude: 51.6722,
    longitude: -116.4577,
    image: "images/journeys/bowlake.svg",
    story: "A quiet pull-off on the Icefields Parkway that turned into an hour — glassy water mirroring Crowfoot Glacier."
  },
  {
    id: 25,
    location: "Peyto Lake, Canada",
    country: "Canada",
    year: 2026,
    date: "July 20, 2026",
    status: "visited",
    latitude: 51.7178,
    longitude: -116.5261,
    image: "images/journeys/peytolake.svg",
    story: "The short walk up to Bow Summit, then that wolf-shaped splash of turquoise far below. Worth every switchback."
  },
  {
    id: 26,
    location: "Waterfowl Lakes, Canada",
    country: "Canada",
    year: 2026,
    date: "July 20, 2026",
    status: "visited",
    latitude: 51.8483,
    longitude: -116.6789,
    image: "images/journeys/waterfowl.svg",
    story: "Two calm lakes under Mount Chephren — we ate lunch on the shore and barely saw another soul."
  },
  {
    id: 27,
    location: "Saskatchewan River Crossing, Canada",
    country: "Canada",
    year: 2026,
    date: "July 20, 2026",
    status: "visited",
    latitude: 51.9672,
    longitude: -116.7178,
    image: "images/journeys/saskcrossing.svg",
    story: "Where the parkway meets the David Thompson Highway — braided rivers, big sky, and a well-earned fuel stop."
  },
  {
    id: 28,
    location: "Columbia Icefield, Canada",
    country: "Canada",
    year: 2026,
    date: "July 21, 2026",
    status: "visited",
    latitude: 52.2201,
    longitude: -117.2242,
    image: "images/journeys/icefield.svg",
    story: "Stood on the Athabasca Glacier in July with a jacket on — ancient ice, meltwater streams, and wind that meant it."
  },

  {
    id: 29,
    location: "Shenzhen, China",
    country: "China Mainland",
    year: 2023,
    date: "May 2, 2023",
    status: "visited",
    latitude: 22.5431,
    longitude: 114.0579,
    image: "images/journeys/shenzhen.svg",
    story: "A city that feels ten years in the future — electric everything, night markets, and the view from Ping An tower."
  },
  {
    id: 30,
    location: "Zhengzhou, China",
    country: "China Mainland",
    year: 2019,
    date: "October 8, 2019",
    status: "visited",
    latitude: 34.7466,
    longitude: 113.6254,
    image: "images/journeys/zhengzhou.svg",
    story: "Gateway to the Yellow River — hand-pulled noodles, and a day trip out to the Shaolin Temple."
  },
  {
    id: 31,
    location: "Nanyang, China",
    country: "China Mainland",
    year: 2019,
    date: "October 10, 2019",
    status: "visited",
    latitude: 32.9908,
    longitude: 112.5283,
    image: "images/journeys/nanyang.svg",
    story: "Slow days visiting family — jade markets, hometown cooking, and evenings by the Bai River."
  },
  {
    id: 32,
    location: "Dongguan, China",
    country: "China Mainland",
    year: 2023,
    date: "May 4, 2023",
    status: "visited",
    latitude: 23.0207,
    longitude: 113.7518,
    image: "images/journeys/dongguan.svg",
    story: "Keyuan Garden in the morning and factory-town energy everywhere else — plus the best roast goose of the trip."
  },
  {
    id: 33,
    location: "Zhaoqing, China",
    country: "China Mainland",
    year: 2023,
    date: "May 7, 2023",
    status: "visited",
    latitude: 23.0472,
    longitude: 112.4651,
    image: "images/journeys/zhaoqing.svg",
    story: "Limestone crags rising straight out of Seven Star Lake — like Guilin in miniature, minus the crowds."
  },
  {
    id: 34,
    location: "Foshan, China",
    country: "China Mainland",
    year: 2023,
    date: "May 6, 2023",
    status: "visited",
    latitude: 23.0218,
    longitude: 113.1219,
    image: "images/journeys/foshan.svg",
    story: "Ancestral Temple, lion dance drums, and dim sum in the birthplace of Cantonese kung fu."
  },
  {
    id: 35,
    location: "Qingyuan, China",
    country: "China Mainland",
    year: 2023,
    date: "May 8, 2023",
    status: "visited",
    latitude: 23.682,
    longitude: 113.0561,
    image: "images/journeys/qingyuan.svg",
    story: "Hot springs in the hills and river fish for dinner — Guangdong's quiet backyard."
  },
  {
    id: 36,
    location: "Shantou, China",
    country: "China Mainland",
    year: 2023,
    date: "May 10, 2023",
    status: "visited",
    latitude: 23.3541,
    longitude: 116.6822,
    image: "images/journeys/shantou.svg",
    story: "Chaoshan beef hotpot, gongfu tea poured properly, and the old treaty-port streets by the sea."
  },
  {
    id: 37,
    location: "Huizhou, China",
    country: "China Mainland",
    year: 2023,
    date: "May 3, 2023",
    status: "visited",
    latitude: 23.1115,
    longitude: 114.4152,
    image: "images/journeys/huizhou.svg",
    story: "West Lake's little sister — pagodas, bridges, and an easy evening walk around the water."
  },
  {
    id: 38,
    location: "Guilin, China",
    country: "China Mainland",
    year: 2023,
    date: "May 12, 2023",
    status: "visited",
    latitude: 25.2736,
    longitude: 110.29,
    image: "images/journeys/guilin.svg",
    story: "A bamboo raft down the Li River between karst peaks — the landscape from every Chinese painting, in real life."
  },
  {
    id: 39,
    location: "Wuhan, China",
    country: "China Mainland",
    year: 2019,
    date: "October 12, 2019",
    status: "visited",
    latitude: 30.5928,
    longitude: 114.3055,
    image: "images/journeys/wuhan.svg",
    story: "Yellow Crane Tower above the Yangtze and hot dry noodles for breakfast — a proper river-city morning."
  },

  {
    id: 40,
    location: "Seattle, USA",
    country: "USA",
    year: 2025,
    date: "April 5, 2025",
    status: "visited",
    latitude: 47.6062,
    longitude: -122.3321,
    image: "images/journeys/seattle.svg",
    story: "An easy drive down from Vancouver — Pike Place fish throwers, the first Starbucks line, and gum wall regret."
  },
  {
    id: 41,
    location: "Kamloops, Canada",
    country: "Canada",
    year: 2025,
    date: "August 15, 2025",
    status: "visited",
    latitude: 50.6745,
    longitude: -120.3273,
    image: "images/journeys/kamloops.svg",
    story: "Sagebrush hills and two rivers meeting — the classic road-trip stop where the coast weather finally gives way to sun."
  },
  {
    id: 42,
    location: "Kelowna, Canada",
    country: "Canada",
    year: 2025,
    date: "August 16, 2025",
    status: "visited",
    latitude: 49.888,
    longitude: -119.496,
    image: "images/journeys/kelowna.svg",
    story: "Okanagan Lake swims, orchard fruit stands, and a lazy winery afternoon — summer at its most golden."
  },

  {
    id: 43,
    location: "Xiachuan Island, China",
    country: "China Mainland",
    year: 2011,
    date: "July 20, 2011",
    status: "visited",
    latitude: 21.6167,
    longitude: 112.5667,
    image: "images/journeys/xiachuan-island.svg",
    story: "Wangfuzhou Beach at dusk, fresh seafood by the pier, and slow island days off the Guangdong coast."
  },

  {
    id: 44,
    location: "Hangzhou, China",
    country: "China Mainland",
    year: 2019,
    date: "April 14, 2019",
    status: "visited",
    latitude: 30.2741,
    longitude: 120.1551,
    image: "images/journeys/hangzhou.svg",
    story: "A misty morning loop around West Lake, longjing tea in the hills, and pagodas floating above the water."
  },

  {
    id: 45,
    location: "Luohe, China",
    country: "China Mainland",
    year: 2019,
    date: "October 9, 2019",
    status: "visited",
    latitude: 33.5816,
    longitude: 114.0166,
    image: "images/journeys/luohe.svg",
    story: "A relaxed stop along the Shali River — riverside walks, night-market snacks, and easygoing Henan hospitality."
  },

  {
    id: 46,
    location: "Zhumadian, China",
    country: "China Mainland",
    year: 2019,
    date: "October 11, 2019",
    status: "visited",
    latitude: 33.0114,
    longitude: 114.0227,
    image: "images/journeys/zhumadian.svg",
    story: "Rolling countryside south of the Huai River — a quiet city break with Mount Chaya rising on the horizon."
  },

  {
    id: 49,
    location: "Squamish, Canada",
    country: "Canada",
    year: 2024,
    date: "June 22, 2024",
    status: "visited",
    latitude: 49.7016,
    longitude: -123.1558,
    image: "images/journeys/squamish.svg",
    story: "The Sea to Sky Gondola above Howe Sound, the Stawamus Chief looming overhead, and windsurfers at the Spit."
  },

  {
    id: 50,
    location: "Whistler, Canada",
    country: "Canada",
    year: 2024,
    date: "June 23, 2024",
    status: "visited",
    latitude: 50.1163,
    longitude: -122.9574,
    image: "images/journeys/whistler.svg",
    story: "Peak 2 Peak gondola between the mountains, patio lunch in the village, and a walk around Lost Lake."
  },

  // ——— To visit ———
  {
    id: 6,
    location: "Hanoi, Vietnam",
    country: "Vietnam",
    year: 2027,
    date: "Planned for 2027",
    status: "to-visit",
    latitude: 21.0278,
    longitude: 105.8342,
    image: "images/journeys/hanoi.svg",
    story: "Old Quarter streets, egg coffee, and a slow boat through Ha Long Bay are all on the list."
  },
  {
    id: 7,
    location: "Singapore",
    country: "Singapore",
    year: 2027,
    date: "Planned for 2027",
    status: "to-visit",
    latitude: 1.3521,
    longitude: 103.8198,
    image: "images/journeys/singapore.svg",
    story: "Hawker centers, Gardens by the Bay after dark, and as much chili crab as one trip allows."
  },
  {
    id: 8,
    location: "Bangkok, Thailand",
    country: "Thailand",
    year: 2027,
    date: "Planned for 2027",
    status: "to-visit",
    latitude: 13.7563,
    longitude: 100.5018,
    image: "images/journeys/bangkok.svg",
    story: "Temples in the morning, street food at night, and a long-tail boat ride along the canals."
  },
  {
    id: 9,
    location: "London, United Kingdom",
    country: "United Kingdom",
    year: 2028,
    date: "Planned for 2028",
    status: "to-visit",
    latitude: 51.5074,
    longitude: -0.1278,
    image: "images/journeys/london.svg",
    story: "Museums, markets, and a proper Sunday roast — plus a day trip out to the countryside."
  },
  {
    id: 10,
    location: "Paris, France",
    country: "France",
    year: 2028,
    date: "Planned for 2028",
    status: "to-visit",
    latitude: 48.8566,
    longitude: 2.3522,
    image: "images/journeys/paris.svg",
    story: "Morning croissants, long museum afternoons, and an evening picnic by the Seine."
  },
  {
    id: 11,
    location: "Mexico City, Mexico",
    country: "Mexico",
    year: 2028,
    date: "Planned for 2028",
    status: "to-visit",
    latitude: 19.4326,
    longitude: -99.1332,
    image: "images/journeys/mexicocity.svg",
    story: "Tacos al pastor, the Frida Kahlo museum, and the pyramids at Teotihuacán just outside the city."
  },
  {
    id: 12,
    location: "Cape Town, South Africa",
    country: "South Africa",
    year: 2029,
    date: "Planned for 2029",
    status: "to-visit",
    latitude: -33.9249,
    longitude: 18.4241,
    image: "images/journeys/capetown.svg",
    story: "Table Mountain by cable car, penguins at Boulders Beach, and a drive down the Cape Peninsula."
  },
  {
    id: 47,
    location: "Seoul, South Korea",
    country: "South Korea",
    year: 2027,
    date: "Planned for 2027",
    status: "to-visit",
    latitude: 37.5665,
    longitude: 126.978,
    image: "images/journeys/seoul.svg",
    story: "Palaces in hanbok season, late-night Korean barbecue, and a sunrise hike up Bukhansan."
  },
  {
    id: 48,
    location: "Tokyo, Japan",
    country: "Japan",
    year: 2027,
    date: "Planned for 2027",
    status: "to-visit",
    latitude: 35.6762,
    longitude: 139.6503,
    image: "images/journeys/tokyo.svg",
    story: "Shibuya crossing at dusk, tiny ramen counters, and a quiet morning at the Meiji Shrine."
  },
  {
    id: 51,
    location: "Quebec City, Canada",
    country: "Canada",
    year: 2026,
    date: "Planned for 2026",
    status: "to-visit",
    latitude: 46.8139,
    longitude: -71.208,
    image: "images/journeys/quebeccity.svg",
    story: "Cobblestone streets of Old Quebec, the Château Frontenac on the skyline, and poutine done properly."
  },
  {
    id: 52,
    location: "Las Vegas, USA",
    country: "USA",
    year: 2026,
    date: "Planned for 2026",
    status: "to-visit",
    latitude: 36.1699,
    longitude: -115.1398,
    image: "images/journeys/lasvegas.svg",
    story: "The Strip lit up at night, the Bellagio fountains, and a day trip out to the Grand Canyon."
  },
  {
    id: 53,
    location: "Los Angeles, USA",
    country: "USA",
    year: 2026,
    date: "Planned for 2026",
    status: "to-visit",
    latitude: 34.0522,
    longitude: -118.2437,
    image: "images/journeys/losangeles.svg",
    story: "Sunset at Santa Monica Pier, a Hollywood Hills hike to the sign, and tacos from a different truck every day."
  },
  {
    id: 54,
    location: "San Francisco, USA",
    country: "USA",
    year: 2026,
    date: "Planned for 2026",
    status: "to-visit",
    latitude: 37.7749,
    longitude: -122.4194,
    image: "images/journeys/sanfrancisco.svg",
    story: "Biking across the Golden Gate Bridge, cable cars over the hills, and sourdough at Fisherman's Wharf."
  }
];
